### ISSUE TITLE
Create Documentation Site

### ISSUE THREAD

**Issue by brklyn8900** [koinos/koinos-docs#1]
As a Koinos engineer, I would like to be able to create beautiful looking documentation which can be deployed quickly and easily.

- [x] Add sphinx (#2)
- [x] Create docs skeleton (#3)
- [x] Add placeholder docs (#4)
- [x] Make it pretty (#5)
